[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[[plugins]]
package = "@netlify/plugin-nextjs"

[build]
  publish = "dist"
  command = "npx vite build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
